FROM kong:3.6-ubuntu

COPY kong/kong.yml /kong/kong.yml

ENV KONG_DATABASE=off
ENV KONG_DECLARATIVE_CONFIG=/kong/kong.yml
ENV KONG_PROXY_LISTEN="0.0.0.0:8080"
ENV KONG_ADMIN_LISTEN="0.0.0.0:8001"
ENV KONG_LOG_LEVEL=info
ENV KONG_PLUGINS=bundled

EXPOSE 8080 8001

HEALTHCHECK --interval=10s --timeout=5s --retries=5 \
    CMD kong health
